# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveFully' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'

  # Pods for LiveFully

  target 'LiveFullyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveFullyUITests' do
    # Pods for testing
  end

end
